### ISSUE TITLE
学长🐮🍺

### ISSUE THREAD

**Issue by haozero484** [imldy/health-data-post#1]
前人栽树后人乘凉

**Comment by imldy** [comment]
有人用我就继续优化一下部署/安装流程，没人用就不维护了。核心功能应该还正常。

**Comment by haozero484** [comment]
学习了，等到我也精进了，一定帮忙维护。

**Comment by wdnmdjvav** [comment]
学长🐮🍺21级新生也来乘凉了,不过现在都要求在qq再发一次已上报，还需要再找个qq机器人吗

**Comment by imldy** [comment]
> 学长🐮🍺21级新生也来乘凉了,不过现在都要求在qq再发一次已上报，还需要再找个qq机器人吗

@wdnmdjvav  需不需要QQ机器人看你安排了，不过其他人在群里发已上报的时候你点个“+1”不就完了嘛😄

**Comment by krtuzg** [comment]
@imldy 我们现在要带学号回复的随意每个人都不一样就莫得加一了= = ！（还有这个怎么回复第一次在github回复没搞明白...

**Comment by labixiaoxin999** [comment]
云函数出错怎么查找错误

**Comment by imldy** [comment]
> 云函数出错怎么查找错误

云函数出错就看云函数的文档，代码出错就贴出报错信息。

**Comment by 1250602390** [comment]
现在更新了，参数少一项，作者是否还会更新呢

**Comment by imldy** [comment]
> 现在更新了，参数少一项，作者是否还会更新呢

具体信息贴一下吧，有空更新

**Comment by 1250602390** [comment]
> > 现在更新了，参数少一项，作者是否还会更新呢
> 
> 具体信息贴一下吧，有空更新

就是填写信息多了一项  第13项 也是和第 11  12 项一样填写温度的

**Comment by imldy** [comment]
> > > 现在更新了，参数少一项，作者是否还会更新呢
> > 
> > 
> > 具体信息贴一下吧，有空更新
> 
> 就是填写信息多了一项 第13项 也是和第 11 12 项一样填写温度的

我需要用用你的智慧山水账号，请联系我邮箱imldy@outlook.com，用完记得更改密码。
原因是我的账号提交过空的健康信息，导致现在服务器无法返回正常上报页面，也就看不到需要提交哪些信息，所以需要你的账号一用。

**Comment by imldy** [comment]
> 现在更新了，参数少一项，作者是否还会更新呢

此话题移至 #3

close issue
